apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  namespace: laravel-multi-pod
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
