apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: laravel-multi-pod
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 80
  selector:
    app: nginx