apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster-ip
  name: cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-php