apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-php
  name: nginx-php
  namespace: laravel-nginx-php-pod
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
      - name: php
        image: localhost:5000/laravel-php
        imagePullPolicy: Always
        ports:
          - containerPort: 9000
        env:
          - name: DB_CONNECTION
            value: sqlite
        volumeMounts:
          - name: app-nginx-public
            mountPath: /var/app
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/bash"
                - "-c"
                - |
                  ln -s /app/public /var/app && \
                  chmod -R 777 storage/* && \
                  cp /app/.env.example /app/.env && \
                  php artisan key:generate && \
                  php artisan migrate --force && \
                  chmod 777 database/database.sqlite
      - image: nginx
        name: nginx
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /up
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /up
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
          - name: app-nginx-public
            mountPath: /var/app
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: app-nginx-public
          emptyDir: {}