apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: laravel-nginx-php-pod
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  selector:
    app: nginx-php